export const IMAGE = {
  binImg: require('../../assets/images/bin.png'),
  carbonCredit: require('../../assets/images/carboncredit.png'),
  circle: require('../../assets/images/circle.png'),
  carbonCreditWhite: require('../../assets/images/carboncreditWhite.png'),
  uploadPic: require('../../assets/images/uploadpic.png'),
  stopwatch: require('../../assets/images/stopwatch.png'),
  amc: require('../../assets/images/amc.png'),
  dmc: require('../../assets/images/dmc.png'),
  circleOfficer: require('../../assets/images/circleOfficer.png'),
  supervisor: require('../../assets/images/supervisor.png'),
  zonalInspector: require('../../assets/images/zonalInspector.png'),
  dummyPic: require('../../assets/images/dummyPic.png'),
  homeHeart: require('../../assets/images/homeHeart.png'),
  userBg: require('../../assets/images/userBg.png'),
  copy: require('../../assets/images/copy.png'),
  key: require('../../assets/images/key.png'),
  settings: require('../../assets/images/settings.png'),
  phone: require('../../assets/images/phone.png'),
  mail: require('../../assets/images/mail.png'),
  edit: require('../../assets/images/edit.png'),
  area: require('../../assets/images/area.png'),
  location: require('../../assets/images/location.png'),
  holding: require('../../assets/images/holding.png'),
  bed: require('../../assets/images/bed.png'),
  toilet: require('../../assets/images/toilet.png'),
  kitchen: require('../../assets/images/kitchen.png'),
  balcony: require('../../assets/images/balcony.png'),
  tag: require('../../assets/images/tag.png'),
  user: require('../../assets/images/user.png'),
  owner: require('../../assets/images/owner.png'),
  logo: require('../../assets/images/logo.png'),
  home: require('../../assets/images/home.png'),
  home_2: require('../../assets/images/home2.png'),
  wallet: require('../../assets/images/wallet.png'),
  wallet_2: require('../../assets/images/wallet2.png'),
  menu: require('../../assets/images/menu.png'),
  menu_2: require('../../assets/images/menu2.png'),
  avatar: require('../../assets/images/avatar.png'),
  avatar_2: require('../../assets/images/avatar2.png'),
  request: require('../../assets/images/request.png'),
  request_2: require('../../assets/images/request2.png'),
  minus: require('../../assets/images/minus.png'),
  plus: require('../../assets/images/plus.png'),
};

export const ANIMATION = {};
