export const STRING = {
  OOPS: 'OOPS!',
  HEY: 'Hey',
  HOUSE_NUM: 'Hno.',
  REACHING_IN: 'Reaching in',
  GET_BIN: 'Get your bins ready!',
  BIN_INSTRUCTIONS: 'Tap to track the garbage collector on the map',
  CHOOSE_ADDRESS: 'Choose address',
  CARBON_WALLET: 'Carbon wallet',
  TOTAL_CC: 'Total Carbon Credits',
  DAILY_GARBAGE_LOG: 'Daily garbage log',
  CUSTOMIZE_SEGREGATED_CARD_VIEW: 'Customize segregated card view',
  MASTER_DASHBOARD: 'Master Dashboard',
  MONTHLY_HISTORY: 'Monthly History',
  VIEW_MONTHLY_PERFORMANCE: 'View monthly performance',
  WASTE_PRODUCED: 'Waste Produced',
  SEGREGATION_STATISTICS: 'Segregation statistics',
  DAILY_LOG: 'Daily log',
  PAYMENT_CENTER: 'Payments Center',
  PAYMENT_METHODS:'Payment Methods',
  TOTAL_PAYABLE_AMOUNT:'Total payable amount',
  CARBON_CREDIT_USING:'Carbon credit using',
  ONLINE:'online',
  PAY:'Pay',
  ENTER_MONTHS_TO_PAY: 'ENTER MONTHS TO PAY',
  PROCEED_TO_PAY: 'Proceed to pay',
  RECORDED_PAYMENT: 'Recorded Payment',
  OKAY: 'Okay',
  TRACK_GARBAGE_COLLECTOR: 'Track garbage collector',
  FEATURE_COMING_SOON: 'This feature is coming soon!',
  CUSTOMIZE_SEG_CARD_VIEW: 'Customize segregated card view',
  TOTAL_WASTE_COLLECTED: 'Total waste collected',
  ONLY_DRY_WASTE: 'Only Dry waste',
  ONLY_WET_WASTE: 'Only Wet waste',
  ONLY_HAZARDOUS_WASTE: 'Only Hazardous waste',
  TOTAL: 'Total',
  DRY: 'Dry',
  WET: 'Wet',
  DEFAULT: 'default',
  ONLY: 'Only',
  SHOW: 'Show',
  WASTE: 'Waste',
  COLLECTED: 'Collected',
  HARZARDOUS: 'Hazardous',
  MIXED_WASTE: 'Mixed waste',
  PICKER_ABSENT: 'Garbage picker absent',
  USER_MISSED: 'You missed',
  REQUESTS_COMPLAINTS: 'Requests / Complaints',
  COMPLAINTS: 'Complaints',
  REQUESTS: 'Requests',
  PHONEBOOK: 'Phonebook',
  POST_A_COMPLAINT: 'Post a complaint',
  POST_COMPLAINT: 'Post complaint',
  MAKE_REQUEST: 'Make a request',
  PAST_COMPLAINT: 'View past complaints status',
  PAST_REQUEST: 'View past requests status',
  REQUEST_FOUND: 'request found',
  LOCATE: 'Locate',
  CHOOSE_CATEGORY: 'Choose Category',
  SUB_CATEGORY: 'Sub Category',
  UPLOAD_PHOTO: 'Upload photo',
  OPTIONAL: '(Optional)',
  MAX_UPLOAD_PIC_SIZE: 'max 100kb',
  ADDITIONAL_INFO: 'Additional info',
  LOCATION: 'Location',
  CHOOSE_DATE: 'Choose a date',
  CHOOSE_LOCATION: 'Choose location',
  CHOOSE_ON_MAP: 'Choose location on map',
  POST_REQUEST: 'Post request',
  STATUS: 'Status',
  SEARCH_HERE: 'Search here',
  ON_THE_JOB: 'On the job',
  RESOLVED: 'Resolved',
  DMC: 'DMC',
  AMC: 'AMC',
  CIRCLE_OFFICER: 'Circle officer',
  ZONAL_SANITORY_INSPECTOR: 'Zonal Sanitory Inspector',
  SUPERVISORS: 'Supervisors',
  ENLISTED: 'enlisted',
  CONTACTS: 'contacts',
  ALL: 'All',

  REQUEST_COMPLAINTS: 'Requests / Complaints',

  EDIT_PROFILE: 'Edit profile',
  EDIT_YOUR_PROFILE: 'Edit your profile',
  TAP_TO_EDIT: 'Tap to edit',
  EDIT_SPOC: 'Edit Spoc',
  UPDATE_SPOC: 'Edit/update SPOC details',
  EDIT_UPDATE_SPOC: 'Edit/update SPOC',
  CONTACT_DETAILS: 'Contact Details',
  ADDRESS: 'Address',
  PHONE: 'Phone',
  EMAIL: 'Email',
  BIN_RFID_DETAILS: 'Bin Rfid Details',
  RESIDENCE: 'Residence',
  OWNED_PROPERTIES: 'Owned Properties',
  SETTINGS: 'Settings',
  BUILDING_DETAILS: 'Building Details',
  CHANGE_PROFILE_PIC: 'Change profile pic',
  LOGIN_PASSWORD: 'Login password',
  TRANSACTION_PASSWORD: 'Transactional password',
  CHANGE_PASSWORD: 'Change password',
  SAVE: 'Save & Exit',
  BUILDING_TYPE: 'Building Type',
  HOLDING: 'Holding ID',
  LOCAL_ADDRESS: 'Local Address',
  BUILDING_RFID: 'Building RFID',
  APPROX_AREA: 'Approx area',
  MEMBER: 'No. of members living',
  KITCHEN: 'No. of kitchens',
  BEDROOMS: 'No. of bedrooms',
  TOILETS: 'No. of Toilets',
  BALCONIES: 'No. of Balconies',
  PEOPLE: 'People',
  TOTAL_DUE: 'Total Due',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  ENTER_FIELD: 'Enter field',
  ENTER_CONTACT: 'Enter contact',
  GENDER: 'Gender',
  CONTACT_NUMBER: 'Contact number',
  ID: 'ID',
  UPDATE: 'Update',
  MALE: 'Male',
  FEMALE: 'Female',
  OTHER: 'Other',
  VIEW_USER_PROFILE: 'View user profile',
  PAYMENT_STATUS: 'Payment Status',
  PAYMENT_HISTORY: 'Payment History',

  WELCOME_TO: 'Welcome to',
  CITYGEN: 'CityGen',
  ENTER_MOBILE_NUMBER: 'Enter your Mobile Number',
  ENTER_OTP: 'Enter OTP',
  NEXT: 'Next',
  SUBMIT: 'Submit',
  RESEND: 'Resend OTP',
};
